# Generated by Django 3.0.2 on 2020-02-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cmts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmts',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
