# Generated by Django 3.0.2 on 2020-02-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200208_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmts',
            name='auth',
        ),
    ]
